<div class="ma_carstore_child category-products">
	<ul class="products-grid">
	<?php
		$_categories=$this->getCurrentChildCategories();
		if($_categories->count()):
			$categorycount = 0;
			foreach ($_categories as $_category):
				$cur_category=Mage::getModel('catalog/category')->load($_category->getId());
				//var_dump($cur_category->getIncludeInMenu());
				if($_category->getIsActive() && $cur_category->getIncludeInMenu()):
					$layer = Mage::getSingleton('catalog/layer');
					$layer->setCurrentCategory($cur_category);
					$catName = $this->getCurrentCategory()->getName();
					if ($categorycount == 0)
						$class = "first";
					elseif ($categorycount == 2)
						$class = "last";
					else
						$class = "";
	?>
					<li class="item <?=$class?>">
						<a href="<?php echo $_category->getURL() ?>" title="<?php echo $this->htmlEscape($_category->getName()) ?>">
							<img src="<?php 
										if ($_category->getImageUrl())
											echo $_category->getImageUrl();
										else
											echo "/skin/frontend/ma_carstore/ma_carstore_child/images/placeholder.png";
									?>" style="max-height:135px;" alt="<?php echo $this->htmlEscape($_category->getName()) ?>" />
						</a>
						<h2 class="product-name">
							<a href="<?php echo $_category->getURL() ?>" title="<?php echo $this->htmlEscape($_category->getName()) ?>"><?php echo $this->htmlEscape($_category->getName()) ?></a>
						</h2>
					</li>
	<?php
					if($categorycount == 2){
						$categorycount = 0;
						echo "</ul>\n\n<ul class=\"products-grid\">";
					}
					else
						$categorycount++;
				endif;
			endforeach;
		endif;
	?>
	</ul>
</div>